(function(){'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={H:!0},ea={};try{ea.__proto__=da;ca=ea.H;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.P=b.prototype}var ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a,b){if(b){var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ma(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:la(a)}}
ka("Promise",function(a){function b(g){this.b=0;this.h=void 0;this.a=[];var k=this.f();try{g(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(k){k(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var k=this;this.f(function(){k.h()})}this.a.push(g)};var e=ia.setTimeout;c.prototype.f=function(g){e(g,0)};c.prototype.h=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var k=0;k<g.length;++k){var l=
g[k];g[k]=null;try{l()}catch(n){this.g(n)}}}this.a=null};c.prototype.g=function(g){this.f(function(){throw g;})};b.prototype.f=function(){function g(n){return function(w){l||(l=!0,n.call(k,w))}}var k=this,l=!1;return{resolve:g(this.O),reject:g(this.g)}};b.prototype.O=function(g){if(g===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.R(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?this.s(g):this.j(g)}};
b.prototype.s=function(g){var k=void 0;try{k=g.then}catch(l){this.g(l);return}"function"==typeof k?this.S(k,g):this.j(g)};b.prototype.g=function(g){this.l(2,g)};b.prototype.j=function(g){this.l(1,g)};b.prototype.l=function(g,k){if(0!=this.b)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.b);this.b=g;this.h=k;this.m()};b.prototype.m=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)h.b(this.a[g]);this.a=null}};var h=new c;b.prototype.R=function(g){var k=this.f();
g.u(k.resolve,k.reject)};b.prototype.S=function(g,k){var l=this.f();try{g.call(k,l.resolve,l.reject)}catch(n){l.reject(n)}};b.prototype.then=function(g,k){function l(z,C){return"function"==typeof z?function(na){try{n(z(na))}catch(oa){w(oa)}}:C}var n,w,pa=new b(function(z,C){n=z;w=C});this.u(l(g,n),l(k,w));return pa};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.u=function(g,k){function l(){switch(n.b){case 1:g(n.h);break;case 2:k(n.h);break;default:throw Error("Unexpected state: "+
n.b);}}var n=this;null==this.a?h.b(l):this.a.push(l)};b.resolve=d;b.reject=function(g){return new b(function(k,l){l(g)})};b.race=function(g){return new b(function(k,l){for(var n=ma(g),w=n.next();!w.done;w=n.next())d(w.value).u(k,l)})};b.all=function(g){var k=ma(g),l=k.next();return l.done?d([]):new b(function(n,w){function pa(na){return function(oa){z[na]=oa;C--;0==C&&n(z)}}var z=[],C=0;do z.push(void 0),C++,d(l.value).u(pa(z.length-1),w),l=k.next();while(!l.done)})};return b});
ka("Object.setPrototypeOf",function(a){return a||fa});var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
ka("Reflect.construct",function(){return qa});var m=this||self;function p(a){return void 0!==a}function q(a){return"string"==typeof a}function r(a){return"number"==typeof a}
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ra=Date.now||function(){return+new Date};
function sa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.W=function(d,e,h){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var ta;var x=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)},ua=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,h=q(a)?a.split(""):a,g=0;g<c;g++)if(g in h){var k=h[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d};function va(a){return Array.prototype.concat.apply([],arguments)}function wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var xa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ya(a,b){if(b)a=a.replace(za,"&amp;").replace(Aa,"&lt;").replace(Ba,"&gt;").replace(Ca,"&quot;").replace(Da,"&#39;").replace(Ea,"&#0;");else{if(!Fa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(za,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Aa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ba,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ca,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Da,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ea,"&#0;"))}return a}
var za=/&/g,Aa=/</g,Ba=/>/g,Ca=/"/g,Da=/'/g,Ea=/\x00/g,Fa=/[\x00&<>"']/;function A(a,b){return-1!=a.indexOf(b)}function Ga(a,b){return a<b?-1:a>b?1:0};var B;a:{var Ha=m.navigator;if(Ha){var Ia=Ha.userAgent;if(Ia){B=Ia;break a}}B=""};function Ja(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Ka="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function La(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Ka.length;h++)c=Ka[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function D(){this.b="";this.f=Ma}D.prototype.w=!0;D.prototype.v=function(){return this.b.toString()};D.prototype.F=!0;D.prototype.a=function(){return 1};var Ma={};function Na(a){var b=new D;b.b=a;return b}Na("about:blank");function E(){this.b="";this.g=Oa;this.f=null}E.prototype.F=!0;E.prototype.a=function(){return this.f};E.prototype.w=!0;E.prototype.v=function(){return this.b.toString()};function F(a){if(a instanceof E&&a.constructor===E&&a.g===Oa)return a.b;t(a);return"type_error:SafeHtml"}function G(a){if(a instanceof E)return a;var b="object"==typeof a,c=null;b&&a.F&&(c=a.a());return Pa(ya(b&&a.w?a.v():String(a)),c)}
function Qa(a){function b(h){"array"==t(h)?y(h,b):(h=G(h),e.push(F(h).toString()),h=h.a(),0==d?d=h:0!=h&&d!=h&&(d=null))}var c=G(Ra),d=c.a(),e=[];y(a,b);return Pa(e.join(F(c).toString()),d)}function Sa(a){return Qa(Array.prototype.slice.call(arguments))}var Oa={};function Pa(a,b){return H(a,b)}function H(a,b){var c=new E;c.b=a;c.f=b;return c}H("<!DOCTYPE html>",0);var Ra=H("",0),Ta=H("<br>",0);var Ua=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=F(Ra);return!b.parentElement});function Va(a,b){if(Ua())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=F(b)};function Wa(a){return a=ya(a,void 0)};function Xa(a,b){var c=Ya;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Za=A(B,"Opera"),I=A(B,"Trident")||A(B,"MSIE"),$a=A(B,"Edge"),ab=A(B,"Gecko")&&!(A(B.toLowerCase(),"webkit")&&!A(B,"Edge"))&&!(A(B,"Trident")||A(B,"MSIE"))&&!A(B,"Edge"),bb=A(B.toLowerCase(),"webkit")&&!A(B,"Edge");function cb(){var a=m.document;return a?a.documentMode:void 0}var db;
a:{var eb="",fb=function(){var a=B;if(ab)return/rv:([^\);]+)(\)|;)/.exec(a);if($a)return/Edge\/([\d\.]+)/.exec(a);if(I)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(bb)return/WebKit\/(\S+)/.exec(a);if(Za)return/(?:Version)[ \/]?(\S+)/.exec(a)}();fb&&(eb=fb?fb[1]:"");if(I){var gb=cb();if(null!=gb&&gb>parseFloat(eb)){db=String(gb);break a}}db=eb}var hb=db,Ya={};
function J(a){return Xa(a,function(){for(var b=0,c=xa(String(hb)).split("."),d=xa(String(a)).split("."),e=Math.max(c.length,d.length),h=0;0==b&&h<e;h++){var g=c[h]||"",k=d[h]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=Ga(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||Ga(0==g[2].length,0==k[2].length)||Ga(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})}var ib;
ib=m.document&&I?cb():void 0;var jb="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""};function kb(){}kb.prototype.a=function(){throw jb;};kb.prototype.b=function(){return this};function K(a,b){this.b={};this.a=[];this.g=this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof K)for(c=a.o(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=K.prototype;f.i=function(){L(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.o=function(){L(this);return this.a.concat()};
f.nb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(M(this.b,c)&&this.b[c]==a)return!0}return!1};f.ob=function(a,b){if(this===a)return!0;if(this.f!=a.f)return!1;b=b||lb;L(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function lb(a,b){return a===b}f.pb=function(){return 0==this.f};f.mb=function(){this.b={};this.g=this.f=this.a.length=0};
function L(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];M(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],M(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return M(this.b,a)?this.b[a]:b};f.set=function(a,b){M(this.b,a)||(this.f++,this.a.push(a),this.g++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.o(),d=0;d<c.length;d++){var e=c[d],h=this.get(e);a.call(b,h,e,this)}};
f.Sb=function(){for(var a=new K,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Rb=function(){L(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.wa=function(){return mb(this,!0)};f.Oa=function(){return mb(this,!1)};function mb(a,b){L(a);var c=0,d=a.g,e=new kb;e.a=function(){if(d!=a.g)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw jb;var h=a.a[c++];return b?h:a.b[h]};return e}
function M(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function nb(a){if(a.i&&"function"==typeof a.i)return a.i();if(q(a))return a.split("");if(u(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ob(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(u(a)||q(a))y(a,b,c);else{if(a.o&&"function"==typeof a.o)var d=a.o();else if(a.i&&"function"==typeof a.i)d=void 0;else if(u(a)||q(a)){d=[];for(var e=a.length,h=0;h<e;h++)d.push(h)}else for(h in d=[],e=0,a)d[e++]=h;e=nb(a);h=e.length;for(var g=0;g<h;g++)b.call(c,e[g],d&&d[g],a)}};var pb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function qb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var h=a[c].substring(0,d);e=a[c].substring(d+1)}else h=a[c];b(h,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function N(a,b){this.b=this.m=this.j="";this.g=null;this.l=this.f="";this.h=this.s=!1;if(a instanceof N){this.h=p(b)?b:a.h;rb(this,a.j);var c=a.m;O(this);this.m=c;c=a.b;O(this);this.b=c;sb(this,a.g);c=a.f;O(this);this.f=c;tb(this,ub(a.a));a=a.l;O(this);this.l=a}else a&&(c=String(a).match(pb))?(this.h=!!b,rb(this,c[1]||"",!0),a=c[2]||"",O(this),this.m=P(a),a=c[3]||"",O(this),this.b=P(a,!0),sb(this,c[4]),a=c[5]||"",O(this),this.f=P(a,!0),tb(this,c[6]||"",!0),a=c[7]||"",O(this),this.l=P(a)):(this.h=
!!b,this.a=new Q(null,this.h))}f=N.prototype;f.toString=function(){var a=[],b=this.j;b&&a.push(R(b,vb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(R(b,vb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.f)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(R(c,"/"==c.charAt(0)?wb:xb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",R(c,yb));return a.join("")};
f.resolve=function(a){var b=new N(this),c=!!a.j;c?rb(b,a.j):c=!!a.m;if(c){var d=a.m;O(b);b.m=d}else c=!!a.b;c?(d=a.b,O(b),b.b=d):c=null!=a.g;d=a.f;if(c)sb(b,a.g);else if(c=!!a.f){if("/"!=d.charAt(0))if(this.b&&!this.f)d="/"+d;else{var e=b.f.lastIndexOf("/");-1!=e&&(d=b.f.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(A(e,"./")||A(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var h=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&h.push(""):".."==k?((1<h.length||1==h.length&&""!=
h[0])&&h.pop(),d&&g==e.length&&h.push("")):(h.push(k),d=!0)}d=h.join("/")}else d=e}c?(O(b),b.f=d):c=""!==a.a.toString();c?tb(b,ub(a.a)):c=!!a.l;c&&(a=a.l,O(b),b.l=a);return b};function rb(a,b,c){O(a);a.j=c?P(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function sb(a,b){O(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.g=b}else a.g=null}function tb(a,b,c){O(a);b instanceof Q?(a.a=b,zb(a.a,a.h)):(c||(b=R(b,Ab)),a.a=new Q(b,a.h));return a}f.Ob=function(a,b){return tb(this,a,b)};
f.ka=function(){return P(this.a.toString())};f.Va=function(){return this.a.toString()};f.Mb=function(a,b){O(this);"array"==t(b)||(b=[String(b)]);Bb(this.a,a,b);return this};f.Ga=function(a){return this.a.i(a)};f.qb=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.g&&null==a.g||this.g==a.g)};f.Cb=function(){O(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ra()).toString(36);O(this);this.a.set("zx",a);return this};
f.Wa=function(a){O(this);Cb(this.a,a);return this};f.Pb=function(a){this.s=a;return this};f.Ab=function(){return this.s};function O(a){if(a.s)throw Error("Tried to modify a read-only Uri");}f.Xa=function(a){this.h=a;this.a&&zb(this.a,a);return this};function P(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function R(a,b,c){return q(a)?(a=encodeURI(a).replace(b,Db),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Db(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var vb=/[#\/\?@]/g,xb=/[#\?:]/g,wb=/[#\?]/g,Ab=/[#\?@]/g,yb=/#/g;function Q(a,b){this.b=this.a=null;this.f=a||null;this.g=!!b}function S(a){a.a||(a.a=new K,a.b=0,a.f&&qb(a.f,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=Q.prototype;f.Ta=function(){S(this);return this.b};f.add=function(a,b){S(this);this.f=null;a=T(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function Cb(a,b){S(a);b=T(a,b);M(a.a.b,b)&&(a.f=null,a.b-=a.a.get(b).length,a=a.a,M(a.b,b)&&(delete a.b[b],a.f--,a.g++,a.a.length>2*a.f&&L(a)))}f.Qa=function(){this.a=this.f=null;this.b=0};f.Ua=function(){S(this);return 0==this.b};function Eb(a,b){S(a);b=T(a,b);return M(a.a.b,b)}f.Ra=function(a){var b=this.i();return 0<=x(b,a)};f.forEach=function(a,b){S(this);this.a.forEach(function(c,d){y(c,function(e){a.call(b,e,d,this)},this)},this)};
f.o=function(){S(this);for(var a=this.a.i(),b=this.a.o(),c=[],d=0;d<b.length;d++)for(var e=a[d],h=0;h<e.length;h++)c.push(b[d]);return c};f.i=function(a){S(this);var b=[];if(q(a))Eb(this,a)&&(b=va(b,this.a.get(T(this,a))));else{a=this.a.i();for(var c=0;c<a.length;c++)b=va(b,a[c])}return b};f.set=function(a,b){S(this);this.f=null;a=T(this,a);Eb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
f.get=function(a,b){if(!a)return b;a=this.i(a);return 0<a.length?String(a[0]):b};function Bb(a,b,c){Cb(a,b);0<c.length&&(a.f=null,a.a.set(T(a,b),wa(c)),a.b+=c.length)}f.toString=function(){if(this.f)return this.f;if(!this.a)return"";for(var a=[],b=this.a.o(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.i(d);for(var h=0;h<d.length;h++){var g=e;""!==d[h]&&(g+="="+encodeURIComponent(String(d[h])));a.push(g)}}return this.f=a.join("&")};
f.Z=function(a){S(this);this.a.forEach(function(b,c){0<=x(a,c)||Cb(this,c)},this);return this};function ub(a){var b=new Q;b.f=a.f;a.a&&(b.a=new K(a.a),b.b=a.b);return b}function T(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b}function zb(a,b){b&&!a.g&&(S(a),a.f=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Cb(this,d),Bb(this,e,c))},a));a.g=b}f.Sa=function(a){for(var b=0;b<arguments.length;b++)ob(arguments[b],function(c,d){this.add(d,c)},this)};var Fb={},Gb={};function U(){throw Error("Do not instantiate directly");}U.prototype.B=null;U.prototype.b=function(){return this.a};U.prototype.toString=function(){return this.a};U.prototype.f=function(){if(this.C!==Gb)throw Error("Sanitized content was not of kind URI.");return Na(this.toString())};function Hb(){U.call(this)}sa(Hb,U);Hb.prototype.C=Fb;var Ib=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.B=d);return c}}(Hb),Jb=/['()]/g;function Kb(a){return"%"+a.charCodeAt(0).toString(16)};var Lb=!I||9<=Number(ib),Mb=!ab&&!I||I&&9<=Number(ib)||ab&&J("1.9.1"),Nb=I&&!J("9"),Ob=I||Za||bb;function V(a,b){this.a=p(a)?a:0;this.b=p(b)?b:0}f=V.prototype;f.gb=function(){return new V(this.a,this.b)};f.hb=function(a){return a instanceof V&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};f.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};f.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};f.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
f.jb=function(a,b){a instanceof V?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),r(b)&&(this.b+=b));return this};f.ib=function(a,b){b=r(b)?b:a;this.a*=a;this.b*=b;return this};f.Gb=function(a,b){a=a*Math.PI/180;b=b||new V(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Pb(a,b){this.width=a;this.height=b}f=Pb.prototype;f.kb=function(){return new Pb(this.width,this.height)};f.ya=function(){return Math.max(this.width,this.height)};f.Ma=function(){return Math.min(this.width,this.height)};f.Db=function(){return 2*(this.width+this.height)};f.aspectRatio=function(){return this.width/this.height};f.lb=function(){return!(this.width*this.height)};f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
f.ca=function(a){return this.width<=a.width&&this.height<=a.height};f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Qb(a,b){var c=r(void 0)?void 0:b;a.width*=b;a.height*=c;return a}f.Ib=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Qb(this,a)};
f.Jb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Qb(this,a)};function Rb(a){return a?new W(X(a)):ta||(ta=new W)}function Sb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Tb(document,"*",a,b);return d||null}
function Ub(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var h=d=0,g;g=b[h];h++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(h=d=0;g=b[h];h++){e=g.className;var k;if(k="function"==typeof e.split)k=0<=x(e.split(/\s+/),c);k&&(a[d++]=g)}a.length=d;return a}return b}
function Tb(a,b,c,d){var e=d||a,h=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(h||c)?e.querySelector(h+(c?"."+c:"")):Ub(a,b,c,d)[0]||null}function Vb(a,b){Ja(b,function(c,d){c&&"object"==typeof c&&c.w&&(c=c.v());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Wb.hasOwnProperty(d)?a.setAttribute(Wb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Wb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Xb(a){a=a.document;a=Yb(a)?a.documentElement:a.body;return new Pb(a.clientWidth,a.clientHeight)}function Zb(a){return a.scrollingElement?a.scrollingElement:!bb&&Yb(a)?a.documentElement:a.body||a.documentElement}
function $b(a){return a.parentWindow||a.defaultView}function ac(a,b,c,d){function e(g){g&&b.appendChild(q(g)?a.createTextNode(g):g)}for(;d<c.length;d++){var h=c[d];u(h)&&!bc(h)?y(cc(h)?wa(h):h,e):e(h)}}function Yb(a){return"CSS1Compat"==a.compatMode}function dc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function ec(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function fc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function bc(a){return v(a)&&0<a.nodeType}function gc(a){return v(a)&&1==a.nodeType}function hc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function ic(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return jc(b,a)}function jc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function X(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function kc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else dc(a),a.appendChild(X(a).createTextNode(String(b)))}function lc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||lc(a,b,c,d))return!0;a=a.nextSibling}return!1}
var mc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},nc={IMG:" ",BR:"\n"};function oc(a){return pc(a)&&qc(a)}function pc(a){return I&&!J("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function qc(a){a=a.tabIndex;return r(a)&&0<=a&&32768>a}
function rc(a){if(Nb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];sc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Nb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function sc(a,b,c){if(!(a.nodeName in mc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in nc)b.push(nc[a.nodeName]);else for(a=a.firstChild;a;)sc(a,b,c),a=a.nextSibling}function cc(a){if(a&&"number"==typeof a.length){if(v(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==t(a))return"function"==typeof a.item}return!1}
function tc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return uc(a,function(h){var g;(g=!e||h.nodeName==e)&&!(g=!c)&&(g=q(h.className))&&(g=0<=x(h.className.split(/\s+/),c));return g},!0,d)}function uc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function W(a){this.a=a||m.document||document}f=W.prototype;f.pa=Rb;f.Kb=function(a){this.a=a};f.la=function(){return this.a};
f.J=function(a){return q(a)?this.a.getElementById(a):a};f.Ka=function(a){return q(a)?this.a.getElementById(a):a};f.T=W.prototype.J;f.cb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};f.K=function(a,b,c){return Ub(this.a,a,b,c)};f.ra=function(a,b,c){return Tb(this.a,a,b,c)};f.sa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Ub(document,"*",a,b)};f.qa=function(a,b){return Sb(a,b||this.a)};
f.La=function(a,b){return Sb(a,b||this.a)};f.U=W.prototype.K;f.Nb=Vb;f.Pa=function(a){return Xb(a||$b(this.a)||window)};f.ma=function(){var a=$b(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Xb(a).height,Yb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
f.I=function(a,b,c){var d=this.a,e=arguments,h=String(e[0]),g=e[1];if(!Lb&&g&&(g.name||g.type)){h=["<",h];g.name&&h.push(' name="',Wa(g.name),'"');if(g.type){h.push(' type="',Wa(g.type),'"');var k={};La(k,g);delete k.type;g=k}h.push(">");h=h.join("")}h=d.createElement(h);g&&(q(g)?h.className=g:"array"==t(g)?h.className=g.join(" "):Vb(h,g));2<e.length&&ac(d,h,e,2);return h};f.V=W.prototype.I;f.bb=function(a){return this.a.createTextNode(String(a))};
f.Y=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),h=e.appendChild(d.createElement("TBODY")),g=0;g<a;g++){for(var k=d.createElement("TR"),l=0;l<b;l++){var n=d.createElement("TD");c&&kc(n,"\u00a0");k.appendChild(n)}h.appendChild(k)}return e};
f.Hb=function(a){var b=this.a;var c=b.createElement("DIV");I?(a=Sa(Ta,a),Va(c,a),c.removeChild(c.firstChild)):Va(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};f.ub=function(){return Yb(this.a)};f.oa=function(){return Zb(this.a)};
f.na=function(){var a=this.a,b=Zb(a);a=$b(a);return I&&J("10")&&a.pageYOffset!=b.scrollTop?new V(b.scrollLeft,b.scrollTop):new V(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};f.ea=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};f.Za=function(a,b){a.appendChild(b)};f.Ya=function(a,b){ac(X(a),a,arguments,1)};f.$a=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
f.Fb=dc;f.tb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};f.sb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};f.rb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};f.eb=ec;f.fb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};f.da=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return ec(a)}};
f.ja=function(a){return Mb&&void 0!=a.children?a.children:ua(a.childNodes,function(b){return 1==b.nodeType})};f.ta=function(a){return p(a.firstElementChild)?a.firstElementChild:fc(a.firstChild,!0)};f.xa=function(a){return p(a.lastElementChild)?a.lastElementChild:fc(a.lastChild,!1)};f.za=function(a){return p(a.nextElementSibling)?a.nextElementSibling:fc(a.nextSibling,!0)};f.Ia=function(a){return p(a.previousElementSibling)?a.previousElementSibling:fc(a.previousSibling,!1)};
f.Aa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};f.Ja=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};f.yb=bc;f.vb=gc;f.Bb=function(a){return v(a)&&a.window==a};f.Ha=function(a){var b;if(Ob&&!(I&&J("9")&&!J("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return gc(b)?b:null};
f.ab=hc;
f.X=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(I&&!(9<=Number(ib))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,h=b.parentNode;return e==h?jc(a,b):!c&&hc(e,b)?-1*ic(a,b):!d&&hc(h,a)?ic(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:h.sourceIndex)}d=X(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};f.$=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var h=[],g=arguments[b];g;)h.unshift(g),g=g.parentNode;d.push(h);e=Math.min(e,h.length)}h=null;for(b=0;b<e;b++){g=d[0][b];for(var k=1;k<c;k++)if(g!=d[k][b])return h;h=g}return h};f.Fa=X;f.ua=function(a){return a.contentDocument||a.contentWindow.document};
f.va=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?$b(c):window}else d=null;b=d}return b}catch(e){}return null};f.Qb=kc;f.Ea=function(a){if("outerHTML"in a)return a.outerHTML;var b=X(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};f.aa=function(a,b){var c=[];return lc(a,b,c,!0)?c[0]:void 0};f.ba=function(a,b){var c=[];lc(a,b,c,!1);return c};f.xb=oc;f.Lb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
f.wb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!pc(a)||qc(a)):oc(a))&&I){var c;"function"!=t(a.getBoundingClientRect)||I&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};f.Na=rc;f.Ca=function(a){return rc(a).length};
f.Da=function(a,b){b=b||X(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(rc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
f.Ba=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in mc))if(3==e.nodeType){var h=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=h.length}else if(e.nodeName in nc)d+=nc[e.nodeName].length;else for(h=e.childNodes.length-1;0<=h;h--)a.push(e.childNodes[h]);v(c)&&(c.Eb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};f.zb=cc;f.ha=tc;f.ga=function(a,b,c){return tc(a,null,b,c)};f.fa=uc;f.ia=function(a){return a.getContext("2d")};var vc={};function wc(a,b){var c=vc[a];if(void 0!==c&&(!c.A||Date.now()<=c.A+3E5))return c.p;c=new Promise(function(e,h){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);h(g)};document.head.appendChild(b)});var d={A:0,p:c};c.catch(function(){return d.A=+new Date});vc[a]=d;return c};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var xc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(xc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Y(a){var b=HTMLElement.call(this)||this;a&&(q(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(Y,HTMLElement);Y.prototype.h=function(){console.warn(this.tagName,"has not implemented update")};Y.prototype.f=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Y.prototype.g=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var yc={};var zc="autohide autoplay controls enablejsapi end hl rel showinfo start video-id".split(" "),Ac=["listType","list"],Bc=null,Cc=!1;function Z(){var a=Y.call(this)||this;a.a=null;a.b=null;return a}ha(Z,Y);f=Z.prototype;
f.connectedCallback=function(){Dc(this);Z.f&&this.D();var a=this.G.bind(this),b=this.D.bind(this);if(p(window.YT))var c=!0;else{Z.b||(Z.b=[]);Z.a||(Z.a=[]);Z.b.push(a);Z.a.push(b);if(!Bc){a=Ec;b=["onYouTubeIframeAPIReady"];var d=m;b[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)!b.length&&p(a)?d[e]=a:d[e]&&d[e]!==Object.prototype[e]?d=d[e]:d=d[e]={};c=void 0===c?null:c;e=new N("//www.youtube.com/iframe_api",void 0);a=document.createElement("script");
a.src=e.toString();c&&(a.type=c);Bc=wc(e.toString(),a);Bc.catch(Fc)}c=!1}c&&this.G()};
f.G=function(){var a=this,b=document.createElement("div");this.appendChild(b);var c={origin:(new URL(document.location.toString())).origin};zc.forEach(function(e){a.hasAttribute(e)&&(c[e]=a.getAttribute(e))});Ac.forEach(function(e){a.hasAttribute(e)&&(c[e]=a.getAttribute(e))});var d={playerVars:c,events:{onReady:this.M.bind(this),onStateChange:this.N.bind(this),onError:this.L.bind(this)}};this.hasAttribute("video-id")&&(d.videoId=this.getAttribute("video-id"));this.a=new YT.Player(b,d)};
f.attributeChangedCallback=function(a,b,c){if(this.a&&"action"===a)switch(c){case "play":this.a.playVideo();break;case "pause":this.a.pauseVideo();break;case "stop":this.a.stopVideo()}};f.M=function(a){if(p(a)&&p(a.target)){this.setAttribute("tabindex","0");a=a.target;var b=a.getVideoData().title;b&&this.setAttribute("aria-label","You are currently on an element that contains a YouTube video titled: "+b+". Continue tabbing to hear the contained options.");"play"===this.getAttribute("action")&&a.playVideo()}};
f.N=function(a){if(p(a)&&p(a.data)&&p(a.target)){var b=a.data,c=a.target;switch(b){case YT.PlayerState.PLAYING:this.setAttribute("action","play");a=null===this.b?"Video Start":"Video Resume";break;case YT.PlayerState.PAUSED:this.setAttribute("action","pause");a="Video Paused";break;case YT.PlayerState.ENDED:this.removeAttribute("action");a="Video Finished";break;default:return}this.b=b;b=c.getVideoData().video_id;c=c.getCurrentTime();r(c)&&(c=Math.floor(c));this.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:a,label:b,value:c},bubbles:!0}))}};f.L=function(){};
f.D=function(){var a={videoId:String(this.getAttribute("video-id"))};a=encodeURIComponent(String(String((a||yc).videoId)));Jb.lastIndex=0;a=Jb.test(a)?a.replace(Jb,Kb):a;var b=Ib('<a href="//www.youtube.com/watch?v='+a+'" class="devsite-video-placeholder"><img src="/_static/images/video-placeholder.svg"/><span>This resource may not be available in your region.</span></a>');a=Rb().a.createElement("DIV");if(v(b))if(b instanceof U){if(b.C!==Fb)throw Error("Sanitized content was not of kind HTML.");b=
H(b.toString(),b.B||null)}else b=G("zSoyz");else b=G(String(b));Va(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));this.appendChild(a)};function Ec(){Z.f=!1;var a=Z.b;delete Z.b;delete Z.a;a.forEach(function(b){return b.call()});delete window.onYouTubeIframeAPIReady}function Fc(){Z.f=!0;var a=Z.a;delete Z.b;delete Z.a;a&&a.forEach(function(b){return b.call()})}f.disconnectedCallback=function(){this.a&&this.a.destroy()};
function Dc(a){a.parentNode.classList.contains("video-wrapper")&&a.setAttribute("inline-small","");var b=a.querySelector(".devsite-embedded-youtube-video");if(b){zc.forEach(function(d){b.hasAttribute("data-"+d)&&a.setAttribute(d,b.getAttribute("data-"+d))});Ac.forEach(function(d){b.hasAttribute("data-"+d)&&a.setAttribute(d,b.getAttribute("data-"+d))});if(b.src){var c=new N(b.src);Ac.forEach(function(d){var e=c.a.get(d);e&&a.setAttribute(d,e)})}a.removeChild(b)}}
ia.Object.defineProperties(Z,{f:{configurable:!0,enumerable:!0,get:function(){return Cc},set:function(a){Cc=a}},observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["action"]}}});Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-youtube",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteYouTube",a)};}).call(this);
