(function(){'use strict';var g;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ba(a)}}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={R:!0},ha={};try{ha.__proto__=fa;ea=ha.R;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.H=b.prototype}var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}function la(){la=function(){};q.Symbol||(q.Symbol=ma)}function na(a,b){this.a=a;ka(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};
var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function oa(){la();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(ba(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
r("Object.setPrototypeOf",function(a){return a||ia});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ca(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return qa});
r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});
r("WeakMap",function(a){function b(h){this.a=(k+=Math.random()+1).toString();if(h){h=p(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){if(!t(h,f)){var l=new c;ka(h,f,{value:l})}}function e(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),m=new a([[h,2],[l,3]]);if(2!=m.get(h)||3!=m.get(l))return!1;m.delete(h);m.set(l,4);return!m.has(h)&&
4==m.get(l)}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var k=0;b.prototype.set=function(h,l){d(h);if(!t(h,f))throw Error("WeakMap key fail: "+h);h[f][this.a]=l;return this};b.prototype.get=function(h){return t(h,f)?h[f][this.a]:void 0};b.prototype.has=function(h){return t(h,f)&&t(h[f],this.a)};b.prototype.delete=function(h){return t(h,f)&&t(h[f],this.a)?delete h[f][this.a]:!1};return b});
r("Map",function(a){function b(){var h={};return h.o=h.next=h.head=h}function c(h,l){var m=h.a;return pa(function(){if(m){for(;m.head!=h.a;)m=m.o;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++k,f.set(l,m)):m="p_"+l;var n=h.b[m];if(n&&t(h.b,m))for(h=0;h<n.length;h++){var aa=n[h];if(l!==l&&aa.key!==aa.key||l===aa.key)return{id:m,list:n,index:h,g:aa}}return{id:m,
list:n,index:-1,g:void 0}}function e(h){this.b={};this.a=b();this.size=0;if(h){h=p(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(p([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(aa){return!1}}())return a;oa();var f=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.b[m.id]=[]);m.g?m.g.value=l:(m.g={next:this.a,o:this.a.o,head:this.a,key:h,value:l},m.list.push(m.g),this.a.o.next=m.g,this.a.o=m.g,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.g&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.g.o.next=h.g.next,h.g.next.o=h.g.o,h.g.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).g};e.prototype.get=function(h){return(h=d(this,h).g)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=
n.value,h.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});var u=this||self;function v(a){return void 0!==a}function w(a){return"string"==typeof a}function ra(a){return"number"==typeof a}function sa(a){if(a&&a!=u)return ta(a.document);null===ua&&(ua=ta(u.document));return ua}var va=/^[\w+/_-]+[=]{0,2}$/,ua=null;function ta(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&va.test(a)?a:""}
function wa(a,b){a=a.split(".");b=b||u;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function xa(){}
function x(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return"array"==x(a)}function ya(a){var b=x(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function za(a,b,c){return a.call.apply(a.bind,arguments)}
function Aa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function Ba(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ba=za:Ba=Aa;return Ba.apply(null,arguments)}
function Ca(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Da=Date.now||function(){return+new Date};function Ea(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Z=function(d,e,f){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[e].apply(d,k)}};var Fa;var Ga=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(w(a))return w(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ha=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=w(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ia=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,f=w(a)?a.split(""):a,k=0;k<c;k++)if(k in f){var h=f[k];b.call(void 0,h,k,a)&&(d[e++]=h)}return d};function Ja(a){return Array.prototype.concat.apply([],arguments)}function Ka(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var La=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ma(a,b){if(b)a=a.replace(Na,"&amp;").replace(Oa,"&lt;").replace(Pa,"&gt;").replace(Qa,"&quot;").replace(Ra,"&#39;").replace(Sa,"&#0;");else{if(!Ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Na,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Oa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Pa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Qa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ra,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Sa,"&#0;"))}return a}
var Na=/&/g,Oa=/</g,Pa=/>/g,Qa=/"/g,Ra=/'/g,Sa=/\x00/g,Ta=/[\x00&<>"']/;function A(a,b){return-1!=a.indexOf(b)}function Ua(a,b){return a<b?-1:a>b?1:0};var B;a:{var Va=u.navigator;if(Va){var Wa=Va.userAgent;if(Wa){B=Wa;break a}}B=""};function Xa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ya(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function $a(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function C(){this.a="";this.c=null;this.b=ab}g=C.prototype;g.G=!0;g.D=function(){return this.a.toString()};g.M=!0;g.v=function(){return 1};g.$=function(a,b){var c=bb(this).toString();c=cb.exec(c);var d=c[3]||"";return db(c[1]+eb("?",c[2]||"",a)+eb("#",d,b))};function bb(a){if(a instanceof C&&a.constructor===C&&a.b===ab)return a.a;x(a);return"type_error:TrustedResourceUrl"}var cb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ab={};function db(a){var b=new C;b.a=a;return b}
function eb(a,b,c){if(null==c)return b;if(w(c))return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=y(e)?e:[e];for(var f=0;f<e.length;f++){var k=e[f];null!=k&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(k)))}}return b};function D(){this.a="";this.b=fb}D.prototype.G=!0;D.prototype.D=function(){return this.a.toString()};D.prototype.M=!0;D.prototype.v=function(){return 1};function gb(a){if(a instanceof D&&a.constructor===D&&a.b===fb)return a.a;x(a);return"type_error:SafeUrl"}var fb={};function hb(a){var b=new D;b.a=a;return b}hb("about:blank");function E(){this.a="";this.c=ib;this.b=null}E.prototype.M=!0;E.prototype.v=function(){return this.b};E.prototype.G=!0;E.prototype.D=function(){return this.a.toString()};function jb(a){if(a instanceof E&&a.constructor===E&&a.c===ib)return a.a;x(a);return"type_error:SafeHtml"}function kb(a){if(a instanceof E)return a;var b="object"==typeof a,c=null;b&&a.M&&(c=a.v());return lb(Ma(b&&a.G?a.D():String(a)),c)}
function mb(a){function b(f){y(f)?Ha(f,b):(f=kb(f),e.push(jb(f).toString()),f=f.v(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=kb(nb),d=c.v(),e=[];Ha(a,b);return lb(e.join(jb(c).toString()),d)}function ob(a){return mb(Array.prototype.slice.call(arguments))}var ib={};function lb(a,b){return pb(a,b)}function pb(a,b){var c=new E;c.a=a;c.b=b;return c}pb("<!DOCTYPE html>",0);var nb=pb("",0),qb=pb("<br>",0);var rb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=jb(nb);return!b.parentElement});function sb(a,b){if(rb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=jb(b)};function tb(a){return a=Ma(a,void 0)};function ub(a){ub[" "](a);return a}ub[" "]=xa;function vb(a,b){var c=wb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var xb=A(B,"Opera"),F=A(B,"Trident")||A(B,"MSIE"),yb=A(B,"Edge"),zb=A(B,"Gecko")&&!(A(B.toLowerCase(),"webkit")&&!A(B,"Edge"))&&!(A(B,"Trident")||A(B,"MSIE"))&&!A(B,"Edge"),G=A(B.toLowerCase(),"webkit")&&!A(B,"Edge"),Ab=A(B,"Macintosh");function Bb(){var a=u.document;return a?a.documentMode:void 0}var Cb;
a:{var Db="",Eb=function(){var a=B;if(zb)return/rv:([^\);]+)(\)|;)/.exec(a);if(yb)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(G)return/WebKit\/(\S+)/.exec(a);if(xb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Eb&&(Db=Eb?Eb[1]:"");if(F){var Fb=Bb();if(null!=Fb&&Fb>parseFloat(Db)){Cb=String(Fb);break a}}Cb=Db}var Gb=Cb,wb={};
function H(a){return vb(a,function(){for(var b=0,c=La(String(Gb)).split("."),d=La(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",h=d[f]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==h[0].length)break;b=Ua(0==k[1].length?0:parseInt(k[1],10),0==h[1].length?0:parseInt(h[1],10))||Ua(0==k[2].length,0==h[2].length)||Ua(k[2],h[2]);k=k[3];h=h[3]}while(0==b)}return 0<=b})}var I;I=u.document&&F?Bb():void 0;var Hb="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function Ib(){}Ib.prototype.next=function(){throw Hb;};Ib.prototype.a=function(){return this};function Jb(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof Jb)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}g=Jb.prototype;g.h=function(){J(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};g.s=function(){J(this);return this.a.concat()};
g.zb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(K(this.b,c)&&this.b[c]==a)return!0}return!1};g.Ab=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||Kb;J(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Kb(a,b){return a===b}g.Bb=function(){return 0==this.c};g.yb=function(){this.b={};this.f=this.c=this.a.length=0};
function J(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];K(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],K(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}g.get=function(a,b){return K(this.b,a)?this.b[a]:b};g.set=function(a,b){K(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};g.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
g.jc=function(){for(var a=new Jb,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};g.ic=function(){J(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};g.Ba=function(){return Lb(this,!0)};g.Ua=function(){return Lb(this,!1)};function Lb(a,b){J(a);var c=0,d=a.f,e=new Ib;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw Hb;var f=a.a[c++];return b?f:a.b[f]};return e}
function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Mb(a){if(a.h&&"function"==typeof a.h)return a.h();if(w(a))return a.split("");if(ya(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Nb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ya(a)||w(a))Ha(a,b,c);else{if(a.s&&"function"==typeof a.s)var d=a.s();else if(a.h&&"function"==typeof a.h)d=void 0;else if(ya(a)||w(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=Mb(a);f=e.length;for(var k=0;k<f;k++)b.call(c,e[k],d&&d[k],a)}};var Ob=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Pb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function Qb(a){this.b=this.m=this.j="";this.f=null;this.l=this.c="";this.i=this.A=!1;if(a instanceof Qb){this.i=v(void 0)?void 0:a.i;Rb(this,a.j);var b=a.m;L(this);this.m=b;b=a.b;L(this);this.b=b;Sb(this,a.f);b=a.c;L(this);this.c=b;Tb(this,Ub(a.a));a=a.l;L(this);this.l=a}else a&&(b=String(a).match(Ob))?(this.i=!1,Rb(this,b[1]||"",!0),a=b[2]||"",L(this),this.m=M(a),a=b[3]||"",L(this),this.b=M(a,!0),Sb(this,b[4]),a=b[5]||"",L(this),this.c=M(a,!0),Tb(this,b[6]||"",!0),a=b[7]||"",L(this),this.l=M(a)):
(this.i=!1,this.a=new Vb(null,this.i))}g=Qb.prototype;g.toString=function(){var a=[],b=this.j;b&&a.push(Wb(b,Xb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(Wb(b,Xb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Wb(c,"/"==c.charAt(0)?Yb:Zb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Wb(c,$b));return a.join("")};
g.bb=function(a){var b=new Qb(this),c=!!a.j;c?Rb(b,a.j):c=!!a.m;if(c){var d=a.m;L(b);b.m=d}else c=!!a.b;c?(d=a.b,L(b),b.b=d):c=null!=a.f;d=a.c;if(c)Sb(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(A(e,"./")||A(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],k=0;k<e.length;){var h=e[k++];"."==h?d&&k==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&""!=f[0])&&
f.pop(),d&&k==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?(L(b),b.c=d):c=""!==a.a.toString();c?Tb(b,Ub(a.a)):c=!!a.l;c&&(a=a.l,L(b),b.l=a);return b};function Rb(a,b,c){L(a);a.j=c?M(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Sb(a,b){L(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Tb(a,b,c){L(a);b instanceof Vb?(a.a=b,ac(a.a,a.i)):(c||(b=Wb(b,bc)),a.a=new Vb(b,a.i));return a}g.fc=function(a,b){return Tb(this,a,b)};
g.oa=function(){return M(this.a.toString())};g.dc=function(a,b){L(this);y(b)||(b=[String(b)]);cc(this.a,a,b);return this};g.Ma=function(a){return this.a.h(a)};g.Cb=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};g.Sb=function(){L(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Da()).toString(36);L(this);this.a.set("zx",a);return this};g.ab=function(a){L(this);dc(this.a,a);return this};
g.gc=function(a){this.A=a;return this};g.Mb=function(){return this.A};function L(a){if(a.A)throw Error("Tried to modify a read-only Uri");}g.cb=function(a){this.i=a;this.a&&ac(this.a,a);return this};function M(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Wb(a,b,c){return w(a)?(a=encodeURI(a).replace(b,ec),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function ec(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}
var Xb=/[#\/\?@]/g,Zb=/[#\?:]/g,Yb=/[#\?]/g,bc=/[#\?@]/g,$b=/#/g;function Vb(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}function N(a){a.a||(a.a=new Jb,a.b=0,a.c&&Pb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}g=Vb.prototype;g.Za=function(){N(this);return this.b};g.add=function(a,b){N(this);this.c=null;a=O(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function dc(a,b){N(a);b=O(a,b);K(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,K(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&J(a)))}g.Wa=function(){this.a=this.c=null;this.b=0};g.$a=function(){N(this);return 0==this.b};function fc(a,b){N(a);b=O(a,b);return K(a.a.b,b)}g.Xa=function(a){var b=this.h();return 0<=Ga(b,a)};g.forEach=function(a,b){N(this);this.a.forEach(function(c,d){Ha(c,function(e){a.call(b,e,d,this)},this)},this)};
g.s=function(){N(this);for(var a=this.a.h(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.h=function(a){N(this);var b=[];if(w(a))fc(this,a)&&(b=Ja(b,this.a.get(O(this,a))));else{a=this.a.h();for(var c=0;c<a.length;c++)b=Ja(b,a[c])}return b};g.set=function(a,b){N(this);this.c=null;a=O(this,a);fc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
g.get=function(a,b){if(!a)return b;a=this.h(a);return 0<a.length?String(a[0]):b};function cc(a,b,c){dc(a,b);0<c.length&&(a.c=null,a.a.set(O(a,b),Ka(c)),a.b+=c.length)}g.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.h(d);for(var f=0;f<d.length;f++){var k=e;""!==d[f]&&(k+="="+encodeURIComponent(String(d[f])));a.push(k)}}return this.c=a.join("&")};
g.ca=function(a){N(this);this.a.forEach(function(b,c){0<=Ga(a,c)||dc(this,c)},this);return this};function Ub(a){var b=new Vb;b.c=a.c;a.a&&(b.a=new Jb(a.a),b.b=a.b);return b}function O(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function ac(a,b){b&&!a.f&&(N(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(dc(this,d),cc(this,e,c))},a));a.f=b}g.Ya=function(a){for(var b=0;b<arguments.length;b++)Nb(arguments[b],function(c,d){this.add(d,c)},this)};var gc={},hc={},ic={};function P(){throw Error("Do not instantiate directly");}P.prototype.J=null;P.prototype.toString=function(){return this.O};P.prototype.a=function(){if(this.K!==hc)throw Error("Sanitized content was not of kind URI.");return hb(this.toString())};function jc(){P.call(this)}Ea(jc,P);jc.prototype.K=gc;function Q(a,b){return null!=a&&a.K===b};function kc(a){if(null!=a)switch(a.J){case 1:return 1;case -1:return-1;case 0:return 0}return null}function lc(a){return Q(a,gc)?a:a instanceof E?mc(jb(a).toString(),a.v()):mc(tb(String(String(a))),kc(a))}var mc=function(a){function b(c){this.O=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.J=d);return c}}(jc);function nc(a){return Q(a,gc)?String(String(a.O).replace(oc,"").replace(pc,"&lt;")).replace(qc,rc):tb(String(a))}
function sc(a){Q(a,hc)||Q(a,ic)?a=R(a):a instanceof D?a=R(gb(a).toString()):a instanceof C?a=R(bb(a).toString()):(a=String(a),a=tc.test(a)?a.replace(uc,vc):"about:invalid#zSoyz");return a}var wc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function rc(a){return wc[a]}
var xc={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function vc(a){return xc[a]}var qc=/[\x00\x22\x27\x3c\x3e]/g,uc=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,tc=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,yc=/^[^&:\/?#]*(?:[\/?#]|$)|^https?:|^data:image\/[a-z0-9+]+;base64,[a-z0-9+\/]+=*$|^blob:/i;function R(a){return String(a).replace(uc,vc)}
var oc=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,pc=/</g;var zc=!F||9<=Number(I),Ac=!zb&&!F||F&&9<=Number(I)||zb&&H("1.9.1"),Bc=F&&!H("9"),Cc=F||xb||G;function S(a,b){this.x=v(a)?a:0;this.a=v(b)?b:0}g=S.prototype;g.sb=function(){return new S(this.x,this.a)};g.tb=function(a){return a instanceof S&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.vb=function(a,b){a instanceof S?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),ra(b)&&(this.a+=b));return this};g.ub=function(a,b){b=ra(b)?b:a;this.x*=a;this.a*=b;return this};g.Xb=function(a,b){a=a*Math.PI/180;b=b||new S(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function Dc(a,b){this.width=a;this.height=b}g=Dc.prototype;g.wb=function(){return new Dc(this.width,this.height)};g.Ea=function(){return Math.max(this.width,this.height)};g.Sa=function(){return Math.min(this.width,this.height)};g.Tb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.xb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ga=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ec(a,b){var c=ra(void 0)?void 0:b;a.width*=b;a.height*=c;return a}g.$b=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Ec(this,a)};
g.ac=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Ec(this,a)};function Fc(a){return a?new T(U(a)):Fa||(Fa=new T)}function Gc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Hc(document,"*",a,b);return d||null}
function Ic(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,k;k=b[f];f++)e==k.nodeName&&(a[d++]=k);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;k=b[f];f++){e=k.className;var h;if(h="function"==typeof e.split)h=0<=Ga(e.split(/\s+/),c);h&&(a[d++]=k)}a.length=d;return a}return b}
function Hc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Ic(a,b,c,d)[0]||null}function Jc(a,b){Xa(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.D());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Kc.hasOwnProperty(d)?a.setAttribute(Kc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Kc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Lc(a){a=a.document;a=Mc(a)?a.documentElement:a.body;return new Dc(a.clientWidth,a.clientHeight)}function Nc(a){return a.scrollingElement?a.scrollingElement:!G&&Mc(a)?a.documentElement:a.body||a.documentElement}
function Oc(a){return a.parentWindow||a.defaultView}function Pc(a,b,c,d){function e(k){k&&b.appendChild(w(k)?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];ya(f)&&!Qc(f)?Ha(Rc(f)?Ka(f):f,e):e(f)}}function Mc(a){return"CSS1Compat"==a.compatMode}function Sc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Tc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Uc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function Qc(a){return z(a)&&0<a.nodeType}function Vc(a){return z(a)&&1==a.nodeType}function Wc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Xc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Yc(b,a)}function Yc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function U(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Zc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Sc(a),a.appendChild(U(a).createTextNode(String(b)))}function $c(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||$c(a,b,c,d))return!0;a=a.nextSibling}return!1}
var ad={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},bd={IMG:" ",BR:"\n"};function cd(a){return dd(a)&&ed(a)}function dd(a){return F&&!H("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function ed(a){a=a.tabIndex;return ra(a)&&0<=a&&32768>a}
function fd(a){if(Bc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];gd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Bc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function gd(a,b,c){if(!(a.nodeName in ad))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in bd)b.push(bd[a.nodeName]);else for(a=a.firstChild;a;)gd(a,b,c),a=a.nextSibling}function Rc(a){if(a&&"number"==typeof a.length){if(z(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==x(a))return"function"==typeof a.item}return!1}
function hd(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return id(a,function(f){var k;(k=!e||f.nodeName==e)&&!(k=!c)&&(k=w(f.className))&&(k=0<=Ga(f.className.split(/\s+/),c));return k},!0,d)}function id(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function T(a){this.a=a||u.document||document}g=T.prototype;g.ua=Fc;g.bc=function(a){this.a=a};g.qa=function(){return this.a};
g.T=function(a){return w(a)?this.a.getElementById(a):a};g.Qa=function(a){return w(a)?this.a.getElementById(a):a};g.W=T.prototype.T;g.jb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.U=function(a,b,c){return Ic(this.a,a,b,c)};g.wa=function(a,b,c){return Hc(this.a,a,b,c)};g.xa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Ic(document,"*",a,b)};g.va=function(a,b){return Gc(a,b||this.a)};
g.Ra=function(a,b){return Gc(a,b||this.a)};g.X=T.prototype.U;g.ec=Jc;g.Va=function(a){return Lc(a||Oc(this.a)||window)};g.ra=function(){var a=Oc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Lc(a).height,Mc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.S=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),k=e[1];if(!zc&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',tb(k.name),'"');if(k.type){f.push(' type="',tb(k.type),'"');var h={};$a(h,k);delete h.type;k=h}f.push(">");f=f.join("")}f=d.createElement(f);k&&(w(k)?f.className=k:y(k)?f.className=k.join(" "):Jc(f,k));2<e.length&&Pc(d,f,e,2);return f};g.Y=T.prototype.S;g.ib=function(a){return this.a.createTextNode(String(a))};
g.ba=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),f=e.appendChild(d.createElement("TBODY")),k=0;k<a;k++){for(var h=d.createElement("TR"),l=0;l<b;l++){var m=d.createElement("TD");c&&Zc(m,"\u00a0");h.appendChild(m)}f.appendChild(h)}return e};
g.Zb=function(a){var b=this.a;var c=b.createElement("DIV");F?(a=ob(qb,a),sb(c,a),c.removeChild(c.firstChild)):sb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Gb=function(){return Mc(this.a)};g.ta=function(){return Nc(this.a)};
g.sa=function(){var a=this.a,b=Nc(a);a=Oc(a);return F&&H("10")&&a.pageYOffset!=b.scrollTop?new S(b.scrollLeft,b.scrollTop):new S(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ia=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.fb=function(a,b){a.appendChild(b)};g.eb=function(a,b){Pc(U(a),a,arguments,1)};g.gb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Wb=Sc;g.Fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Db=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.kb=Tc;g.lb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ha=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Tc(a)}};
g.na=function(a){return Ac&&void 0!=a.children?a.children:Ia(a.childNodes,function(b){return 1==b.nodeType})};g.ya=function(a){return v(a.firstElementChild)?a.firstElementChild:Uc(a.firstChild,!0)};g.Ca=function(a){return v(a.lastElementChild)?a.lastElementChild:Uc(a.lastChild,!1)};g.Fa=function(a){return v(a.nextElementSibling)?a.nextElementSibling:Uc(a.nextSibling,!0)};g.Oa=function(a){return v(a.previousElementSibling)?a.previousElementSibling:Uc(a.previousSibling,!1)};
g.Ga=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Pa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Kb=Qc;g.Hb=Vc;g.Nb=function(a){return z(a)&&a.window==a};g.Na=function(a){var b;if(Cc&&!(F&&H("9")&&!H("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Vc(b)?b:null};
g.hb=Wc;
g.aa=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(F&&!(9<=Number(I))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Yc(a,b):!c&&Wc(e,b)?-1*Xc(a,b):!d&&Wc(f,a)?Xc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=U(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};g.da=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],k=arguments[b];k;)f.unshift(k),k=k.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){k=d[0][b];for(var h=1;h<c;h++)if(k!=d[h][b])return f;f=k}return f};g.La=U;g.za=function(a){return a.contentDocument||a.contentWindow.document};
g.Aa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Oc(c):window}else d=null;b=d}return b}catch(e){}return null};g.hc=Zc;g.Ka=function(a){if("outerHTML"in a)return a.outerHTML;var b=U(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ea=function(a,b){var c=[];return $c(a,b,c,!0)?c[0]:void 0};g.fa=function(a,b){var c=[];$c(a,b,c,!1);return c};g.Jb=cd;g.cc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Ib=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!dd(a)||ed(a)):cd(a))&&F){var c;"function"!=x(a.getBoundingClientRect)||F&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ta=fd;g.Ia=function(a){return fd(a).length};
g.Ja=function(a,b){b=b||U(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(fd(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ha=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in ad))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in bd)d+=bd[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);z(c)&&(c.Vb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Lb=Rc;g.la=hd;g.ka=function(a,b,c){return hd(a,null,b,c)};g.ja=id;g.ma=function(a){return a.getContext("2d")};function jd(a){var b=new URL(document.location.toString());a=new URL(a,b.origin);if(a.hostname!==b.hostname)return a;var c=new Qb(b.href),d=new Qb(a.href);"tenant hl authuser acting_user mv mh skip_cache".split(" ").forEach(function(e){var f=c.a.get(e);f&&!d.a.get(e)&&(L(d),d.a.set(e,f))});a.search=d.a.toString();return a};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var kd=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(kd&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function V(a){var b=HTMLElement.call(this)||this;a&&(w(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ja(V,HTMLElement);V.prototype.P=function(){console.warn(this.tagName,"has not implemented update")};V.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
V.prototype.A=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var ld=!F||9<=Number(I),md=!F||9<=Number(I),nd=F&&!H("9"),od=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",xa,b),u.removeEventListener("test",xa,b)}catch(c){}return a}();function pd(){this.u=this.u;this.b=this.b}g=pd.prototype;g.u=!1;g.V=function(){return this.u};g.pa=pd.prototype.V;g.N=function(){this.u||(this.u=!0,this.L())};g.Ub=function(a){a=Ca(qd,a);this.u?v(void 0)?a.call(void 0):a():(this.b||(this.b=[]),this.b.push(v(void 0)?Ba(a,void 0):a))};g.L=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function qd(a){a&&"function"==typeof a.N&&a.N()};function rd(a,b){this.type=a;this.w=this.target=b;this.m=this.b=!1;this.P=!0}rd.prototype.F=function(){this.b=!0};rd.prototype.B=function(){this.m=!0;this.P=!1};function W(a,b){rd.call(this,a?a.type:"");this.relatedTarget=this.w=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.j=this.i=0;this.key="";this.c=this.f=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.l=null;this.A=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.w=b;if(b=a.relatedTarget){if(zb){a:{try{ub(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.i=G||void 0!==a.offsetX?a.offsetX:a.layerX,this.j=G||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.f=a.keyCode||0;this.key=a.key||"";this.c=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.A=Ab?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=w(a.pointerType)?a.pointerType:sd[a.pointerType]||"";this.l=a.state;this.a=a;a.defaultPrevented&&this.B()}}Ea(W,rd);var td=[1,4,2],sd={2:"touch",3:"pen",4:"mouse"};
W.prototype.kc=function(){return(ld?0==this.a.button:"click"==this.type?!0:!!(this.a.button&td[0]))&&!(G&&Ab&&this.ctrlKey)};W.prototype.F=function(){W.H.F.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};W.prototype.B=function(){W.H.B.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};W.prototype.Yb=function(){return this.a};var ud="closure_listenable_"+(1E6*Math.random()|0),vd=0;function wd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++vd;this.C=this.I=!1}function xd(a){a.C=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function yd(a){this.src=a;this.a={};this.b=0}g=yd.prototype;g.ob=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var k=zd(a,b,d,e);-1<k?(b=a[k],c||(b.I=!1)):(b=new wd(b,this.src,f,!!d,e),b.I=c,a.push(b));return b};
g.qb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=zd(e,b,c,d);return-1<b?(xd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.rb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,xd(d[e]);delete this.a[c];this.b--}return b};g.Da=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.pb=function(a,b){var c=v(a),d=c?a.toString():"",e=v(b);return Ya(this.a,function(f){for(var k=0;k<f.length;++k)if(!(c&&f[k].type!=d||e&&f[k].capture!=b))return!0;return!1})};function zd(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Ad="closure_lm_"+(1E6*Math.random()|0),Bd={},Cd=0;function Dd(a,b,c,d,e){if(d&&d.once)return Ed(a,b,c,d,e);if(y(b)){for(var f=0;f<b.length;f++)Dd(a,b[f],c,d,e);return null}c=Fd(c);return a&&a[ud]?Gd(a,b,c,z(d)?!!d.capture:!!d,e):Hd(a,b,c,!1,d,e)}
function Hd(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=z(e)?!!e.capture:!!e,h=Id(a);h||(a[Ad]=h=new yd(a));c=h.add(b,c,d,k,f);if(c.a)return c;d=Jd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)od||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Kd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Cd++;return c}
function Jd(){var a=Ld,b=md?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Ed(a,b,c,d,e){if(y(b)){for(var f=0;f<b.length;f++)Ed(a,b[f],c,d,e);return null}c=Fd(c);return a&&a[ud]?a.m(b,c,z(d)?!!d.capture:!!d,e):Hd(a,b,c,!0,d,e)}
function Md(a){if(!ra(a)&&a&&!a.C){var b=a.src;if(b&&b[ud])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Kd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Cd--;if(c=Id(b)){d=a.type;if(d in c.a){var e=c.a[d],f=Ga(e,a),k;(k=0<=f)&&Array.prototype.splice.call(e,f,1);k&&(xd(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Ad]=null)}else xd(a)}}}function Kd(a){return a in Bd?Bd[a]:Bd[a]="on"+a}
function Nd(a,b,c,d){var e=!0;if(a=Id(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.C&&(f=Od(f,d),e=e&&!1!==f)}return e}function Od(a,b){var c=a.listener,d=a.b||a.src;a.I&&Md(a);return c.call(d,b)}
function Ld(a,b){if(a.C)return!0;if(!md){var c=b||wa("window.event");b=new W(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.w;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.b&&0<=e;e--){b.w=c[e];var f=Nd(c[e],a,!0,b);d=d&&f}for(e=0;!b.b&&e<c.length;e++)b.w=c[e],f=Nd(c[e],a,!1,b),d=d&&f}return d}return Od(a,new W(b,this))}
function Id(a){a=a[Ad];return a instanceof yd?a:null}var Pd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Fd(a){if("function"==x(a))return a;a[Pd]||(a[Pd]=function(b){return a.handleEvent(b)});return a[Pd]};function Qd(a){pd.call(this);this.c=a;this.a={}}Ea(Qd,pd);var Rd=[];function Sd(a,b,c,d){Gd(a,b,c,d,void 0)}g=Qd.prototype;g.Pb=function(a,b,c,d,e){return Gd(this,a,b,c,d,e)};function Gd(a,b,c,d,e,f){y(c)||(c&&(Rd[0]=c.toString()),c=Rd);for(var k=0;k<c.length;k++){var h=Dd(b,c[k],d||a.handleEvent,e||!1,f||a.c||a);if(!h)break;a.a[h.key]=h}return a}g.nb=function(a,b,c,d){return Td(this,a,b,c,d)};g.Ob=function(a,b,c,d,e){return Td(this,a,b,c,d,e)};
function Td(a,b,c,d,e,f){if(y(c))for(var k=0;k<c.length;k++)Td(a,b,c[k],d,e,f);else{b=Ed(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.Qb=function(a,b,c,d){Gd(b,a,c,d,this.c||this);return this};g.Rb=function(a,b,c,d,e){Gd(b,a,c,d,e||this.c||this);return this};g.mb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Ud(a,b,c,d,e,f){if(y(c))for(var k=0;k<c.length;k++)Ud(a,b,c[k],d,e,f);else d=d||a.handleEvent,e=z(e)?!!e.capture:!!e,f=f||a.c||a,d=Fd(d),e=!!e,b&&b[ud]?c=b.l(c,d,e,f):b?(b=Id(b))?(c=b.a[c.toString()],b=-1,c&&(b=zd(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Md(c),delete a.a[c.key])}g.lc=function(a,b,c,d,e){Ud(b,a,c,d,e||this.c||this,this);return this};function Vd(a){Xa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Md(b)},a);a.a={}}g.L=function(){Qd.H.L.call(this);Vd(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Wd(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||u,e=d.document,f=sa(d);f&&(a.nonce=f);if("help"==a.flow){var k=wa("document.location.href",d);!a.helpCenterContext&&k&&(a.helpCenterContext=k.substring(0,1200));k=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(k=1200>=h.length)&&(a.psdJson=h)}k||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(k=d.GOOGLE_FEEDBACK_START)k.apply(d,b);else{d=c+"/load.js?";for(var l in a)b=
a[l],null!=b&&!z(b)&&(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=Fc(e).a.createElement("SCRIPT");f&&a.setAttribute("nonce",f);f=db(d);a.src=bb(f);(f=sa())&&a.setAttribute("nonce",f);e.body.appendChild(a)}}var Xd=["userfeedback","api","startFeedback"],X=u;Xd[0]in X||"undefined"==typeof X.execScript||X.execScript("var "+Xd[0]);for(var Y;Xd.length&&(Y=Xd.shift());)!Xd.length&&v(Wd)?X[Y]=Wd:X[Y]&&X[Y]!==Object.prototype[Y]?X=X[Y]:X=X[Y]={};function Z(){var a=V.call(this,["devsite-dialog"])||this;a.b=new Qd;a.c=!1;a.a=null;return a}ja(Z,V);
Z.prototype.connectedCallback=function(){if(!this.c){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=p(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=p(d.value);d=e.next().value;e=e.next().value;a.hasAttribute(d)&&(this.setAttribute(e,a.getAttribute(d)),
a.removeAttribute(d))}c=p(c.entries());for(b=c.next();!b.done;b=c.next())d=p(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(this.setAttribute(b,a.getAttribute(b)),a.removeAttribute(b)):this.setAttribute(b,d);a.classList.remove("google-feedback")}this.hasAttribute("project-name")||(a=document.querySelector('meta[property="og:site_name"]'))&&this.setAttribute("project-name",a.getAttribute("content"));this.hasAttribute("project-icon")?this.setAttribute("project-icon",jd(this.getAttribute("project-icon")).href):
(a=document.querySelector('link[rel="apple-touch-icon"]'))&&this.setAttribute("project-icon",a.getAttribute("href"));c=this.getAttribute("project-name")||"";var f=this.getAttribute("project-icon");b=this.getAttribute("project-icon-name");d=this.getAttribute("project-feedback-url");e=this.getAttribute("project-support-url");a='<devsite-dialog><devsite-feedback-contents class="devsite-dialog-contents"><h3>Send feedback about...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>This page</div><div class="devsite-feedback-item-type">Documentation feedback';
b?f='<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+lc(b)+"</div>":f?(Q(f,hc)||Q(f,ic)?f=R(f):f instanceof D?f=R(gb(f).toString()):f instanceof C?f=R(bb(f).toString()):(f=String(f),f=yc.test(f)?f.replace(uc,vc):"about:invalid#zSoyz"),f='<img src="'+nc(f)+'">'):f="";a+="</div></a><a"+(d?' href="'+nc(sc(d))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+
(b?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+'">'+f+"</div><div>"+lc(c)+'</div><div class="devsite-feedback-item-type">';a+="Product feedback</div></a></div>";e&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',c='Need help? Visit our <a href="'+(nc(sc(e))+'">support page</a>.'),a=a+c+"</span></div>");c=mc(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>Close</button></div></devsite-feedback-contents></devsite-dialog>');
a=Fc().a.createElement("DIV");if(z(c))if(c instanceof P){if(c.K!==gc)throw Error("Sanitized content was not of kind HTML.");c=pb(c.toString(),c.J||null)}else c=kb("zSoyz");else c=kb(String(c));sb(a,c);1==a.childNodes.length&&(c=a.firstChild,1==c.nodeType&&(a=c));this.a=a;this.c=!0}Yd(this)};Z.prototype.disconnectedCallback=function(){Vd(this.b)};
function Yd(a){Sd(a.b,a,"click",function(b){b.B();b.F();a.a&&(document.body.appendChild(a.a),a.a.setAttribute("open",""),b={action:"click",category:a.getAttribute("data-category")||"Site-Wide Custom Events",label:a.getAttribute("data-label")},Zd(a,b))});a.a&&(Array.from(a.a.querySelectorAll("[feedback-type]")).forEach(function(b){Sd(a.b,b,"click",function(c){c.B();c.F();c=c.w;var d=c.getAttribute("feedback-type");d={context:a.getAttribute("context"),type:d};var e={productId:a.getAttribute("product-id"),
locale:DevsiteApp.getLocale(),bucket:a.getAttribute("bucket"),productVersion:a.getAttribute("version"),callback:a.i.bind(a),onLoadCallback:a.f.bind(a)};c={action:"click",label:c.getAttribute("data-label"),category:c.getAttribute("data-category")||"Site-Wide Custom Events"};Zd(a,c);Wd(e,d)})}),Sd(a.b,a.a.querySelector("button[feedback-cancel]"),"click",function(){a.f();var b=a.a.querySelector("button[feedback-cancel]");b={action:"click",label:b.getAttribute("data-label"),category:b.getAttribute("data-category")||
"Site-Wide Custom Events"};Zd(a,b)}),Sd(a.b,a.a,"devsite-dialog-hide",function(){Tc(a.a)}))}Z.prototype.f=function(){this.a.removeAttribute("open");Tc(this.a)};Z.prototype.i=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return Tc(a)})};function Zd(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteFeedback",a)};}).call(this);
