(function(){'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={N:!0},fa={};try{fa.__proto__=ea;da=fa.N;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=ca;
function la(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.D=b.prototype}var p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ma="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function q(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ma(c,a,{configurable:!0,writable:!0,value:b})}}
q("Promise",function(a){function b(g){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{g(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(k){k(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(g)};var e=p.setTimeout;c.prototype.c=function(g){e(g,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var k=0;k<g.length;++k){var l=
g[k];g[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(g){this.c(function(){throw g;})};b.prototype.c=function(){function g(m){return function(t){l||(l=!0,m.call(k,t))}}var k=this,l=!1;return{resolve:g(this.B),reject:g(this.f)}};b.prototype.B=function(g){if(g===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.C(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?this.o(g):this.h(g)}};
b.prototype.o=function(g){var k=void 0;try{k=g.then}catch(l){this.f(l);return}"function"==typeof k?this.I(k,g):this.h(g)};b.prototype.f=function(g){this.i(2,g)};b.prototype.h=function(g){this.i(1,g)};b.prototype.i=function(g,k){if(0!=this.b)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.b);this.b=g;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)f.b(this.a[g]);this.a=null}};var f=new c;b.prototype.C=function(g){var k=this.c();
g.w(k.resolve,k.reject)};b.prototype.I=function(g,k){var l=this.c();try{g.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(g,k){function l(x,C){return"function"==typeof x?function(ha){try{m(x(ha))}catch(ia){t(ia)}}:C}var m,t,ja=new b(function(x,C){m=x;t=C});this.w(l(g,m),l(k,t));return ja};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.w=function(g,k){function l(){switch(m.b){case 1:g(m.g);break;case 2:k(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?f.b(l):this.a.push(l)};b.resolve=d;b.reject=function(g){return new b(function(k,l){l(g)})};b.race=function(g){return new b(function(k,l){for(var m=n(g),t=m.next();!t.done;t=m.next())d(t.value).w(k,l)})};b.all=function(g){var k=n(g),l=k.next();return l.done?d([]):new b(function(m,t){function ja(ha){return function(ia){x[ha]=ia;C--;0==C&&m(x)}}var x=[],C=0;do x.push(void 0),C++,d(l.value).w(ja(x.length-1),t),l=k.next();while(!l.done)})};return b});
function na(){na=function(){};p.Symbol||(p.Symbol=oa)}function pa(a,b){this.a=a;ma(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.a};var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function qa(){na();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ma(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}});qa=function(){}}function ra(a){qa();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function sa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}
function ta(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.c=this.g=0;this.i=this.b=null}function ua(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}h=ta.prototype;h.F=function(a){this.j=a};function va(a,b){a.b={K:b,M:!0};a.a=a.g||a.c}h.return=function(a){this.b={return:a};this.a=this.c};h.ua=function(a){this.b={u:a};this.a=this.c};h.Ma=function(a,b){a=n(a);var c=a.next();sa(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,a=c.value,this.a=b,{value:a}};
h.u=function(a){this.a=a};h.Da=function(a,b){this.g=a;void 0!=b&&(this.c=b)};h.Ea=function(a){this.g=0;this.c=a||0};h.wa=function(a,b){this.a=a;this.g=b||0};h.R=function(a){this.g=a||0;a=this.b.K;this.b=null;return a};h.S=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.g=a||0;this.c=b||0};h.va=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.M?this.a=this.g||this.c:void 0!=b.u&&this.c<b.u?(this.a=b.u,this.b=null):this.a=this.c:this.a=a};h.V=function(a){return new wa(a)};
function wa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}wa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function xa(a){this.a=new ta;this.b=a}function ya(a,b){ua(a.a);var c=a.a.f;if(c)return za(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return r(a)}
function za(a,b,c,d){try{var e=b.call(a.a.f,c);sa(e);if(!e.done)return a.a.h=!1,e;var f=e.value}catch(g){return a.a.f=null,va(a.a,g),r(a)}a.a.f=null;d.call(a.a,f);return r(a)}function r(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,va(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.M)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function Aa(a){this.next=function(b){ua(a.a);a.a.f?b=za(a,a.a.f.next,b,a.a.F):(a.a.F(b),b=r(a));return b};this.throw=function(b){ua(a.a);a.a.f?b=za(a,a.a.f["throw"],b,a.a.F):(va(a.a,b),b=r(a));return b};this.return=function(b){return ya(a,b)};qa();this[Symbol.iterator]=function(){return this}}function Ba(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});q("Object.setPrototypeOf",function(a){return a||ka});
var Ca=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();q("Reflect.construct",function(){return Ca});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});var u=this||self;function v(a){return"string"==typeof a}function Da(){}
function w(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return"array"==w(a)}function Ea(a){var b=w(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Fa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Ga=Date.now||function(){return+new Date};
function Ha(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.P=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var A=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(v(a))return v(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ia=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function Ja(a){return Array.prototype.concat.apply([],arguments)}
function Ka(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var La=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function B(a,b){return-1!=a.indexOf(b)}function Ma(a,b){return a<b?-1:a>b?1:0};var D;a:{var Na=u.navigator;if(Na){var Oa=Na.userAgent;if(Oa){D=Oa;break a}}D=""};function Pa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Qa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function Ra(a){Ra[" "](a);return a}Ra[" "]=Da;function Sa(a){var b=Ta;return Object.prototype.hasOwnProperty.call(b,"9")?b["9"]:b["9"]=a("9")};var Ua=B(D,"Opera"),E=B(D,"Trident")||B(D,"MSIE"),Va=B(D,"Edge"),Wa=B(D,"Gecko")&&!(B(D.toLowerCase(),"webkit")&&!B(D,"Edge"))&&!(B(D,"Trident")||B(D,"MSIE"))&&!B(D,"Edge"),F=B(D.toLowerCase(),"webkit")&&!B(D,"Edge"),Xa=B(D,"Macintosh");function Ya(){var a=u.document;return a?a.documentMode:void 0}var Za;
a:{var $a="",ab=function(){var a=D;if(Wa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Va)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(Ua)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(E){var bb=Ya();if(null!=bb&&bb>parseFloat($a)){Za=String(bb);break a}}Za=$a}var cb=Za,Ta={};
function db(){return Sa(function(){for(var a=0,b=La(String(cb)).split("."),c=La("9").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;a=Ma(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||Ma(0==f[2].length,0==g[2].length)||Ma(f[2],g[2]);f=f[3];g=g[3]}while(0==a)}return 0<=a})}var eb;eb=u.document&&E?Ya():void 0;function fb(a,b){var c=[];gb(a,b,c,!1);return c}function gb(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||gb(a,b,c,d))return!0;a=a.nextSibling}return!1}function hb(a){return E&&!db()?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function ib(a){a=a.tabIndex;return"number"==typeof a&&0<=a&&32768>a}
function jb(a,b,c){if(!b&&!c)return null;var d=b?String(b).toUpperCase():null;return kb(a,function(e){var f;(f=!d||e.nodeName==d)&&!(f=!c)&&(f=v(e.className))&&(f=0<=A(e.className.split(/\s+/),c));return f})}function kb(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};var lb="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function mb(){}mb.prototype.next=function(){throw lb;};mb.prototype.a=function(){return this};function G(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof G)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}h=G.prototype;h.l=function(){H(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};h.m=function(){H(this);return this.a.concat()};
h.qa=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(I(this.b,c)&&this.b[c]==a)return!0}return!1};h.T=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||nb;H(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function nb(a,b){return a===b}h.ra=function(){return 0==this.c};h.pa=function(){this.b={};this.f=this.c=this.a.length=0};
function H(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];I(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],I(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}h.get=function(a,b){return I(this.b,a)?this.b[a]:b};h.set=function(a,b){I(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};h.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
h.Ja=function(){for(var a=new G,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};h.Ia=function(){H(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};h.Y=function(){return ob(this,!0)};h.aa=function(){return ob(this,!1)};function ob(a,b){H(a);var c=0,d=a.f,e=new mb;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw lb;var f=a.a[c++];return b?f:a.b[f]};return e}
function I(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function pb(a){if(a.l&&"function"==typeof a.l)return a.l();if(v(a))return a.split("");if(Ea(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function qb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ea(a)||v(a))Ia(a,b,c);else{if(a.m&&"function"==typeof a.m)var d=a.m();else if(a.l&&"function"==typeof a.l)d=void 0;else if(Ea(a)||v(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=pb(a);f=e.length;for(var g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var rb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function sb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function J(a){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof J){this.g=a.g;tb(this,a.h);var b=a.j;K(this);this.j=b;b=a.b;K(this);this.b=b;ub(this,a.f);b=a.c;K(this);this.c=b;L(this,vb(a.a));a=a.i;K(this);this.i=a}else a&&(b=String(a).match(rb))?(this.g=!1,tb(this,b[1]||"",!0),a=b[2]||"",K(this),this.j=M(a),a=b[3]||"",K(this),this.b=M(a,!0),ub(this,b[4]),a=b[5]||"",K(this),this.c=M(a,!0),L(this,b[6]||"",!0),a=b[7]||"",K(this),this.i=M(a)):(this.g=!1,this.a=new N(null,
this.g))}h=J.prototype;h.toString=function(){var a=[],b=this.h;b&&a.push(O(b,wb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(O(b,wb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(O(c,"/"==c.charAt(0)?xb:yb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",O(c,zb));return a.join("")};
h.resolve=function(a){var b=new J(this),c=!!a.h;c?tb(b,a.h):c=!!a.j;if(c){var d=a.j;K(b);b.j=d}else c=!!a.b;c?(d=a.b,K(b),b.b=d):c=null!=a.f;d=a.c;if(c)ub(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(B(e,"./")||B(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(K(b),b.c=d):c=""!==a.a.toString();c?L(b,vb(a.a)):c=!!a.i;c&&(a=a.i,K(b),b.i=a);return b};function tb(a,b,c){K(a);a.h=c?M(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function ub(a,b){K(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function L(a,b,c){K(a);b instanceof N?(a.a=b,Ab(a.a,a.g)):(c||(b=O(b,Bb)),a.a=new N(b,a.g));return a}h.Ga=function(a,b){return L(this,a,b)};
h.W=function(){return M(this.a.toString())};h.ga=function(){return this.a.toString()};h.Fa=function(a,b){K(this);y(b)||(b=[String(b)]);Cb(this.a,a,b);return this};h.$=function(a){return this.a.l(a)};h.sa=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};h.Ba=function(){K(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Ga()).toString(36);K(this);this.a.set("zx",a);return this};
h.ha=function(a){K(this);P(this.a,a);return this};h.Ha=function(a){this.o=a;return this};h.ta=function(){return this.o};function K(a){if(a.o)throw Error("Tried to modify a read-only Uri");}h.ia=function(a){this.g=a;this.a&&Ab(this.a,a);return this};function M(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function O(a,b,c){return v(a)?(a=encodeURI(a).replace(b,Db),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Db(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var wb=/[#\/\?@]/g,yb=/[#\?:]/g,xb=/[#\?]/g,Bb=/[#\?@]/g,zb=/#/g;function N(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}function Q(a){a.a||(a.a=new G,a.b=0,a.c&&sb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=N.prototype;h.ea=function(){Q(this);return this.b};h.add=function(a,b){Q(this);this.c=null;a=R(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function P(a,b){Q(a);b=R(a,b);I(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,I(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&H(a)))}h.ba=function(){this.a=this.c=null;this.b=0};h.fa=function(){Q(this);return 0==this.b};function Eb(a,b){Q(a);b=R(a,b);return I(a.a.b,b)}h.ca=function(a){var b=this.l();return 0<=A(b,a)};h.forEach=function(a,b){Q(this);this.a.forEach(function(c,d){Ia(c,function(e){a.call(b,e,d,this)},this)},this)};
h.m=function(){Q(this);for(var a=this.a.l(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.l=function(a){Q(this);var b=[];if(v(a))Eb(this,a)&&(b=Ja(b,this.a.get(R(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Ja(b,a[c])}return b};h.set=function(a,b){Q(this);this.c=null;a=R(this,a);Eb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
h.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function Cb(a,b,c){P(a,b);0<c.length&&(a.c=null,a.a.set(R(a,b),Ka(c)),a.b+=c.length)}h.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};
h.U=function(a){Q(this);this.a.forEach(function(b,c){0<=A(a,c)||P(this,c)},this);return this};function vb(a){var b=new N;b.c=a.c;a.a&&(b.a=new G(a.a),b.b=a.b);return b}function R(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Ab(a,b){b&&!a.f&&(Q(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(P(this,d),Cb(this,e,c))},a));a.f=b}h.da=function(a){for(var b=0;b<arguments.length;b++)qb(arguments[b],function(c,d){this.add(d,c)},this)};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Fb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Fb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function S(a){var b=HTMLElement.call(this)||this;a&&(v(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}la(S,HTMLElement);S.prototype.I=function(){console.warn(this.tagName,"has not implemented update")};S.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
S.prototype.C=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var Gb=!E||9<=Number(eb),Hb=!E||9<=Number(eb),Ib=E&&!db(),Jb=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",Da,b),u.removeEventListener("test",Da,b)}catch(c){}return a}();function T(){this.s=this.s;this.b=this.b}h=T.prototype;h.s=!1;h.O=function(){return this.s};h.X=T.prototype.O;h.J=function(){this.s||(this.s=!0,this.H())};h.Ca=function(a){a=Fa(Kb,a);this.s?a():(this.b||(this.b=[]),this.b.push(a))};h.H=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Kb(a){a&&"function"==typeof a.J&&a.J()};function U(a,b){this.type=a;this.b=this.target=b;this.o=this.c=!1;this.C=!0}U.prototype.f=function(){this.c=!0};U.prototype.A=function(){this.o=!0;this.C=!1};function V(a,b){U.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.i=this.h=0;this.key="";this.g=this.L=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.j=null;this.B=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(Wa){a:{try{Ra(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.h=F||void 0!==a.offsetX?a.offsetX:a.layerX,this.i=F||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.L=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.B=Xa?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=v(a.pointerType)?a.pointerType:Lb[a.pointerType]||"";this.j=a.state;this.a=a;a.defaultPrevented&&this.A()}}Ha(V,U);var Mb=[1,4,2],Lb={2:"touch",3:"pen",4:"mouse"};
V.prototype.La=function(){return(Gb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Mb[0]))&&!(F&&Xa&&this.ctrlKey)};V.prototype.f=function(){V.D.f.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};V.prototype.A=function(){V.D.A.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ib)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};V.prototype.I=function(){return this.a};var W="closure_listenable_"+(1E6*Math.random()|0),Nb=0;function Ob(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Nb;this.v=this.G=!1}function X(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Pb(a){this.src=a;this.a={};this.b=0}h=Pb.prototype;h.la=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};h.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Qb(a,b,d,e);-1<g?(b=a[g],c||(b.G=!1)):(b=new Ob(b,this.src,f,!!d,e),b.G=c,a.push(b));return b};
h.na=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Qb(e,b,c,d);return-1<b?(X(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};h.oa=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,X(d[e]);delete this.a[c];this.b--}return b};h.Z=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
h.ma=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Qa(this.a,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};function Qb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Rb="closure_lm_"+(1E6*Math.random()|0),Sb={},Tb=0;function Ub(a,b,c,d,e){if(d&&d.once)return Vb(a,b,c,d,e);if(y(b)){for(var f=0;f<b.length;f++)Ub(a,b[f],c,d,e);return null}c=Wb(c);return a&&a[W]?Y(a,b,c,z(d)?!!d.capture:!!d,e):Xb(a,b,c,!1,d,e)}
function Xb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=z(e)?!!e.capture:!!e,k=Yb(a);k||(a[Rb]=k=new Pb(a));c=k.add(b,c,d,g,f);if(c.a)return c;d=Zb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Jb||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent($b(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Tb++;return c}
function Zb(){var a=ac,b=Hb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Vb(a,b,c,d,e){if(y(b)){for(var f=0;f<b.length;f++)Vb(a,b[f],c,d,e);return null}c=Wb(c);return a&&a[W]?a.B(b,c,z(d)?!!d.capture:!!d,e):Xb(a,b,c,!0,d,e)}
function bc(a){if("number"!=typeof a&&a&&!a.v){var b=a.src;if(b&&b[W])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($b(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Tb--;if(c=Yb(b)){d=a.type;if(d in c.a){var e=c.a[d],f=A(e,a),g;(g=0<=f)&&Array.prototype.splice.call(e,f,1);g&&(X(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Rb]=null)}else X(a)}}}
function $b(a){return a in Sb?Sb[a]:Sb[a]="on"+a}function cc(a,b,c,d){var e=!0;if(a=Yb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.v&&(f=dc(f,d),e=e&&!1!==f)}return e}function dc(a,b){var c=a.listener,d=a.b||a.src;a.G&&bc(a);return c.call(d,b)}
function ac(a,b){if(a.v)return!0;if(!Hb){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new V(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=cc(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=cc(d[e],a,!1,b),c=
c&&f}return c}return dc(a,new V(b,this))}function Yb(a){a=a[Rb];return a instanceof Pb?a:null}var ec="__closure_events_fn_"+(1E9*Math.random()>>>0);function Wb(a){if("function"==w(a))return a;a[ec]||(a[ec]=function(b){return a.handleEvent(b)});return a[ec]};function fc(a){T.call(this);this.c=a;this.a={}}Ha(fc,T);var gc=[];function hc(a,b,c,d){Y(a,b,c,d,void 0)}h=fc.prototype;h.ya=function(a,b,c,d,e){return Y(this,a,b,c,d,e)};function Y(a,b,c,d,e,f){y(c)||(c&&(gc[0]=c.toString()),c=gc);for(var g=0;g<c.length;g++){var k=Ub(b,c[g],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}h.ka=function(a,b,c,d){return ic(this,a,b,c,d)};h.xa=function(a,b,c,d,e){return ic(this,a,b,c,d,e)};
function ic(a,b,c,d,e,f){if(y(c))for(var g=0;g<c.length;g++)ic(a,b,c[g],d,e,f);else{b=Vb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.za=function(a,b,c,d){Y(b,a,c,d,this.c||this);return this};h.Aa=function(a,b,c,d,e){Y(b,a,c,d,e||this.c||this);return this};h.ja=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function jc(a,b,c,d,e,f){if(y(c))for(var g=0;g<c.length;g++)jc(a,b,c[g],d,e,f);else d=d||a.handleEvent,e=z(e)?!!e.capture:!!e,f=f||a.c||a,d=Wb(d),e=!!e,b&&b[W]?c=b.o(c,d,e,f):b?(b=Yb(b))?(c=b.a[c.toString()],b=-1,c&&(b=Qb(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(bc(c),delete a.a[c.key])}h.Ka=function(a,b,c,d,e){jc(b,a,c,d,e||this.c||this,this);return this};function kc(a){Pa(a.a,function(b,c){this.a.hasOwnProperty(c)&&bc(b)},a);a.a={}}h.H=function(){fc.D.H.call(this);kc(this)};
h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var lc=!1;function mc(a){if((a=a.target)&&1==a.nodeType){var b=a.getAttribute("data-modal-dialog-id");b?(b=document.getElementById(b))&&b instanceof Z&&(b.g=a,b.open=!0):(a.classList.contains("devsite-dialog-close")||jb(a,null,"devsite-dialog-close"))&&(a=jb(a,"devsite-dialog"))&&a instanceof Z&&(a.open=!1)}}function Z(){var a=S.call(this)||this;a.i=!1;a.f=null;a.c=null;a.a=[];a.g=null;a.b=new fc;a.h=!1;return a}la(Z,S);
Z.prototype.attributeChangedCallback=function(a,b,c){if("open"===a)if(null!==c)this.setAttribute("aria-modal","true"),this.setAttribute("aria-role","dialog"),this.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})),this.dispatchEvent(new CustomEvent("devsite-dialog-show",{bubbles:!0})),this.f=this.parentElement,this.c=this.nextElementSibling,document.body.appendChild(this),(a=this.querySelector("h3"))&&this.scrollHeight>this.clientHeight?(a.hasAttribute("tabindex")||a.setAttribute("tabindex",
-1),a.focus()):this.a.length&&this.a[0].focus();else{a=n(this.querySelectorAll("devsite-youtube"));for(b=a.next();!b.done;b=a.next())b=b.value,b.hasAttribute("action")&&"play"==b.getAttribute("action")&&b.setAttribute("action","pause");this.removeAttribute("aria-modal");this.removeAttribute("aria-role");this.c&&this.c.parentElement==this.f?this.f.insertBefore(this,this.c):this.f.appendChild(this);(a=this.querySelector("h3"))&&-1==a.getAttribute("tabindex")&&a.removeAttribute("tabindex");this.g&&this.g.focus();
this.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));this.dispatchEvent(new CustomEvent("devsite-dialog-hide",{bubbles:!0}))}};
Z.prototype.connectedCallback=function(){var a=this;hc(this.b,document.body,"devsite-before-page-change",function(){a.open=!1});hc(this.b,document.body,"devsite-sitemask-hidden",function(){a.open=!1});lc||(lc=!0,document.addEventListener("click",mc));if(!this.i){this.i=!0;var b=null;Array.from(this.children).some(function(e){if(e.classList.contains("devsite-dialog"))return b=e,!0});b&&(nc(this,b),this.removeChild(b));for(var c=n(this.querySelectorAll(".devsite-dialog-buttons > a")),d=c.next();!d.done;d=
c.next())d=d.value,d.hasAttribute("tabindex")||d.setAttribute("tabindex",0)}(c=this.querySelector("h3"))&&this.setAttribute("aria-label",c.innerText);oc(this);hc(this.b,this,"keydown",function(e){if(("Tab"==e.key||9==e.L)&&a.a.includes(document.activeElement)){var f=a.a.indexOf(document.activeElement);e.shiftKey?a.a[0==f?a.a.length-1:f-1].focus():a.a[f==a.a.length-1?0:f+1].focus();e.A()}});this.h||pc(this)};
function pc(a){var b,c;Ba(new Aa(new xa(function(d){if(1==d.a){b=new J((new URL(document.location.toString())).href);c=b.a.get("dialogOnLoad");if(a.id!=="devsite-dialog-onload-"+c)return d.u(0);a.h=!0;var e=DevsiteApp.whenReady();d.a=3;return{value:e}}a.open=!0;d.a=0})))}function nc(a,b){var c=b.getAttribute("id");c&&a.setAttribute("id",c);a.className=b.className;for(a.classList.remove("devsite-dialog");b.childNodes[0];)a.appendChild(b.childNodes[0])}
function oc(a){a.a=fb(a,function(b){var c;if(c=b instanceof HTMLElement){c="A"==b.tagName&&b.hasAttribute("href")||"INPUT"==b.tagName||"TEXTAREA"==b.tagName||"SELECT"==b.tagName||"BUTTON"==b.tagName?!b.disabled&&(!hb(b)||ib(b)):hb(b)&&ib(b);var d;c&&E?("function"!=w(b.getBoundingClientRect)||E&&null==b.parentElement?d={height:b.offsetHeight,width:b.offsetWidth}:d=b.getBoundingClientRect(),d=null!=d&&0<d.height&&0<d.width):d=c;c=d||b.hasAttribute("tabindex")}return c}).sort(function(b,c){b=b.hasAttribute("tabindex")?
parseInt(b.getAttribute("tabindex"),10):0;c=c.hasAttribute("tabindex")?parseInt(c.getAttribute("tabindex"),10):0;return 0<b&&0<c?c-b:0<b?-1:0<c?1:0})}Z.prototype.disconnectedCallback=function(){kc(this.b)};p.Object.defineProperties(Z.prototype,{open:{configurable:!0,enumerable:!0,set:function(a){a?this.setAttribute("open",this.getAttribute("open")||""):this.removeAttribute("open")}}});p.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["open"]}}});
Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;try{window.customElements.define("devsite-dialog",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteDialog",a)};}).call(this);
